src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="orders")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\Column(type="date_immutable")
     * @Assert\GreaterThan("today")
     */
    private $start;

    /**
     * @ORM\Column(type="date_immutable")
     * @Assert\GreaterThanOrEqual(propertyPath="start")
     */
    private $end;

    /**
     * @ORM\ManyToMany(targetEntity=Item::class, inversedBy="orders", orphanRemoval=false)
     */
    private $items;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity=OrderState::class, mappedBy="order", cascade={"persist"}, orphanRemoval=true)
     */
    private $orderStates;

    /**
     * @ORM\OneToMany(targetEntity=OrderDocument::class, mappedBy="document_order", orphanRemoval=true)
     */
    private $documents;

    /**
     * @ORM\ManyToOne(targetEntity=Teacher::class, inversedBy="orders")
     */
    private $teacher;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\ManyToMany(targetEntity=Equipment::class, inversedBy="orders")
     */
    private $equipment;

    /**
     * @ORM\OneToMany(targetEntity=UsedItem::class, mappedBy="ordr")
     */
    private $usedItems;


    public function __construct()
    {
        $this->items = new ArrayCollection();
        $this->orderStates = new ArrayCollection();
        $this->documents = new ArrayCollection();
        $this->setCreatedAt(new \DateTimeImmutable());
        $this->equipment = new ArrayCollection();
        $this->usedItems = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClient(): User|UserInterface
    {
        return $this->client;
    }

    public function setClient(User|UserInterface $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getStart(): ?DateTimeImmutable
    {
        return $this->start;
    }

    public function setStart(\DateTime $start): self
    {
        $this->start = DateTimeImmutable::createFromMutable($start);

        return $this;
    }

    public function getEnd(): ?DateTimeImmutable
    {
        return $this->end;
    }

    public function setEnd(\DateTime $end): self
    {

        $this->end = DateTimeImmutable::createFromMutable($end);

        return $this;
    }

    /**
     * @return Collection|Item[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(Item $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
        }

        return $this;
    }

    public function getItemsCount(): int
    {
        return $this->items->count();
    }

    public function removeItem(Item $item): self
    {
        $this->items->removeElement($item);

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|OrderState[]
     */
    public function getOrderStates(): Collection
    {
        return $this->orderStates;
    }

    public function addOrderState(OrderState $orderState): self
    {
        if (!$this->orderStates->contains($orderState)) {
            $this->orderStates[] = $orderState;
            $orderState->setOrder($this);
        }

        return $this;
    }

    public function removeOrderState(OrderState $orderState): self
    {
        if ($this->orderStates->removeElement($orderState)) {
            // set the owning side to null (unless already changed)
            if ($orderState->getOrder() === $this) {
                $orderState->setOrder(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|OrderDocument[]
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    public function addDocument(OrderDocument $document): self
    {
        if (!$this->documents->contains($document)) {
            $this->documents[] = $document;
            $document->setDocumentOrder($this);
        }

        return $this;
    }

    public function removeDocument(OrderDocument $document): self
    {
        if ($this->documents->removeElement($document)) {
            // set the owning side to null (unless already changed)
            if ($document->getDocumentOrder() === $this) {
                $document->setDocumentOrder(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getClient() . " - " . $this->getCreatedAt()->format("d.m.Y H:i");
    }

    public function getTeacher(): ?Teacher
    {
        return $this->teacher;
    }

    public function setTeacher(?Teacher $teacher): self
    {
        $this->teacher = $teacher;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return Collection|Equipment[]
     */
    public function getEquipment(): Collection
    {
        return $this->equipment;
    }

    /**
     * @param Equipment[]|Collection $equipments
     * @return Order
     */
    public function setEquipment(mixed $equipments)
    {
        foreach ($equipments as $equipment) {
            $this->addEquipment($equipment);
        }
        return $this;
    }

    public function addEquipment(Equipment $equipment): self
    {
        if (!$this->equipment->contains($equipment)) {
            $this->equipment[] = $equipment;
        }

        return $this;
    }

    public function removeEquipment(Equipment $equipment): self
    {
        $this->equipment->removeElement($equipment);

        return $this;
    }

    public function isConfilct(DateTimeImmutable $start, DateTimeImmutable $end)
    {
        $thisStart = $this->getStart()->getTimestamp();
        $thisEnd = $this->getEnd()->getTimestamp();
        return ($start->getTimestamp() >= $thisStart && $end->getTimestamp() <= $thisEnd) || ($start->getTimestamp() <= $thisEnd && $start->getTimestamp() >= $thisStart) || ($end->getTimestamp() >= $thisStart && $end->getTimestamp() <= $thisEnd) || ($start->getTimestamp() <= $thisStart && $end->getTimestamp() >= $thisEnd);
    }

    public function getInitialZeroId(): string
    {
        $base = "0000";
        $base = substr($base, -0, -strlen((string)$this->getId()));
        $base .= $this->getId();
        return $base;
    }

    public function getCurrentStatus(): OrderState {
        return $this->getOrderStates()->last();
    }

    /**
     * @return Collection|UsedItem[]
     */
    public function getUsedItems(): Collection
    {
        return $this->usedItems;
    }

    public function addUsedItem(UsedItem $usedItem): self
    {
        if (!$this->usedItems->contains($usedItem)) {
            $this->usedItems[] = $usedItem;
            $usedItem->setOrdr($this);
        }

        return $this;
    }

    public function removeUsedItem(UsedItem $usedItem): self
    {
        if ($this->usedItems->removeElement($usedItem)) {
            // set the owning side to null (unless already changed)
            if ($usedItem->getOrdr() === $this) {
                $usedItem->setOrdr(null);
            }
        }

        return $this;
    }

    public function getErrorState(): ?OrderState
    {
        foreach ($this->getOrderStates() as $orderState) {
            if($orderState->getState()->getSlug() === "error") return $orderState;
        }
        return null;
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\Equipment;
use App\Entity\Message;
use App\Entity\Order;
use App\Entity\OrderState;
use App\Form\MessageFormType;
use App\Form\OrderType;
use App\Repository\ItemRepository;
use App\Repository\OrderRepository;
use App\Repository\StateRepository;
use App\Services\CartManagerService;
use App\Services\OrderManager;
use App\Services\SettingsAccessCheckerService;
use App\Services\UserNotifierService;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityManagerInterface;
use Monolog\Logger;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class OrderController extends AbstractController
{

    public function __construct(
        private SettingsAccessCheckerService $accessCheckerService
    )
    {
    }

    #[Route("/mes-commandes", name: "orders.user")]
    public function myOrders(StateRepository $stateRepository, OrderRepository $orderRepository): Response
    {
        return $this->render('pages/my-orders.html.twig', [
            'orders' => $orderRepository->findByUser($this->getUser()),
            'states' => $stateRepository->findAll(),
            'menu' => 'myOrder'
        ]);
    }

    #[Route("/mes-commandes/{id}", name: "orders.user.show")]
    public function myOrder(Order $order): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        if($order->getClient()->getId() !== $this->getUser()->getId()) return $this->redirectToRoute('orders.user', [], Response::HTTP_SEE_OTHER);
        return $this->render('pages/order/show-order.html.twig', [
            'order' => $order,
            'menu' => 'myOrder',
            'tab' => 'show.summary'
        ]);
    }

    #[Route("/mes-commandes/{id}/equipement", name: "orders.user.show.equipment")]
    public function myOrderEquipment(Order $order): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        if($order->getClient()->getId() !== $this->getUser()->getId()) return $this->redirectToRoute('orders.user', [], Response::HTTP_SEE_OTHER);
        return $this->render('pages/order/equipment-order.html.twig', [
            'order' => $order,
            'menu' => 'myOrder',
            'tab' => 'show.equipment'
        ]);
    }

    #[Route("/mes-commandes/{id}/error", name: "orders.user.show.error")]
    public function myOrderError(Order $order, EntityManagerInterface $entityManager, Request $request): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        if($order->getClient()->getId() !== $this->getUser()->getId() && !$this->isGranted('ROLE_ADMIN')) return $this->redirectToRoute('orders.user', [], Response::HTTP_SEE_OTHER);
        if(is_null($order->getErrorState())) return $this->redirectToRoute('orders.user.show', ['id' => $order->getId()], Response::HTTP_SEE_OTHER);
        if(is_null($order->getErrorState()->getMessage())) {
            $this->addFlash('error', "Un problème est survenu veuillez contacter un administrateur.");
            return $this->redirectToRoute('orders.user.show', ['id' => $order->getId()], Response::HTTP_SEE_OTHER);
        }
        $orderMessage = $order->getErrorState()->getMessage();

        if(!is_null($orderMessage->getMessage())) return $this->render('pages/order/error-order.html.twig', [
            'order' => $order,
            'menu' => 'myOrder',
            'tab' => 'show.error',
            'messageRequest' => $orderMessage
        ]);


        $message = (new Message())
            ->setTitle("Réponse à l'erreur de la commande n°". $orderMessage->getOrder()->getInitialZeroId())
            ->setCreatedBy($this->getUser())
        ;

        $form = $this->createForm(MessageFormType::class, $message);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $message
                ->setTitle("Réponse à l'erreur de la commande n°". $orderMessage->getOrder()->getInitialZeroId())
                ->setCreatedBy($this->getUser());
            $orderMessage->setMessage($message);
            $entityManager->flush();

            return $this->redirectToRoute('orders.user.show', ['id' => $orderMessage->getOrder()->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('pages/order/error-order_form.html.twig', [
            'order' => $order,
            'menu' => 'myOrder',
            'tab' => 'show.error',
            'form' => $form,
            'messageRequest' => $orderMessage
        ]);
    }

    #[Route("/mes-commandes/{id}/chronologie", name: "orders.user.show.chronology")]
    public function myOrderChronology(Order $order): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        if($order->getClient()->getId() !== $this->getUser()->getId()) return $this->redirectToRoute('orders.user', [], Response::HTTP_SEE_OTHER);
        return $this->render('pages/order/chronology-order.html.twig', [
            'order' => $order,
            'menu' => 'myOrder',
            'tab' => 'show.chronology'
        ]);
    }

    #[Route("/mes-commandes/{id}/action", name: "orders.user.show.actions")]
    public function myOrderActions(Order $order): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        if($order->getClient()->getId() !== $this->getUser()->getId() || !$this->isGranted('ROLE_ADMIN')) return $this->redirectToRoute('orders.user', [], Response::HTTP_SEE_OTHER);
        return $this->render('pages/order/show-order.html.twig', [
            'order' => $order,
            'menu' => 'myOrder',
            'tab' => 'show.actions'
        ]);
    }

    #[Route("/nouvelle-commande", name: "order.new")]
    public function new(Request $request, EntityManagerInterface $entityManager, OrderManager $orderManager, UserNotifierService $notifierService, CartManagerService $cartManagerService): Response
    {

        if(!$this->accessCheckerService->access('authorize.order.new', )) {
            $this->addFlash("error", "Les commandes ont été supendues temporairement.");
            return $this->redirectToRoute('user.cart', [], Response::HTTP_SEE_OTHER);
        }

        $order = new Order();
        $form = $this->createForm(OrderType::class, $order);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $order->setClient($this->getUser());
            $order->setEquipment($this->getUser()->getCartEquipment());

            $checkResult = $orderManager->checkConflicts($order);

            if($checkResult['hasConflict']){
                $this->addFlash('error', "Un ou plusieurs objets sélectionné ne sont pas disponible !");
                return $this->renderForm("pages/order/new.html.twig", [
                    'form' => $form,
                    'conflicts' => $checkResult['conflict'],
                ], (new Response())->setStatusCode(Response::HTTP_SEE_OTHER));
            }

            $order = $orderManager->createOrder($order, $checkResult['conflict']);

            $cartManagerService->flushUserCart();
            $entityManager->persist($order);
            $entityManager->flush();

            $notifierService->clientOrderReceived($order->getId());
            $notifierService->staffOrderReceived($order->getId());

            $this->addFlash('success', "Votre commande a été crée, vérifier vos emails !");
            return $this->redirectToRoute('orders.user', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm("pages/order/new.html.twig", [
            'form' => $form
        ]);
    }


}

templates/pages/order/_new_order_form.html.twig
{{ form_start(form, {attr: {class: 'stack-large stacked'}}) }}
<div class="card p3">
    <div class="stack">
        <section class="grid">
            {{ form_row(form.title) }}
            {{ form_row(form.start) }}
            {{ form_row(form.end) }}
            {{ form_row(form.teacher) }}
        </section>
        <section>
            <div class="section-title">
                Brève description du projet
            </div>
            {{ form_row(form.description) }}
        </section>
    </div>
</div>
<div class="text-right">
    <button type="submit" class="btn-primary">Étape suivante</button>
</div>
{{ form_end(form) }}

templates/pages/order/chronology-order.html.twig
{% extends 'base.html.twig' %}

{% set lightBody = true %}
{% set headerContrast = true %}

{% block body %}
    <div class="page-header-accent container" style="padding-bottom: 200px">
        <h1 class="h1">{{ order.title }}</h1>
    </div>
    <div class="show-order-page">
        <div class="order-card">
            <div class="order-card__header">
                {{ include('components/_my-order_nav.html.twig') }}
            </div>
            <div class="order-card__body">
                <h2 class="order-card__title h2 mb4">Chronologie</h2>
                <div class="timeline grid">
                    <div class="card full timeline-element">
                        <div class="card__body stack">
                            <h2 class="card__title">Création de la commande</h2>
                        </div>
                        <footer class="card__footer text-small">
                            <div class="text-truncate">
                                {{ icon('event') }} {{ order.createdAt | date("d.m.Y") }}
                            </div>
                            <div>
                                {{ icon('person') }} {{ order.client }}
                            </div>
                        </footer>
                    </div>
                    {% for status in order.orderStates %}
                        <div class="card full timeline-element">
                            <div class="card__body stack">
                                <h2 class="card__title">Changement de statut => <span style="color: #{{ status.state.color }}">{{ status.state.name }}</span></h2>
                                <p>"{{ status.comments }}"</p>
                                {% if status.state.slug is same as("error") %}
                                    {% if status.message is not same as(null) %}
                                        {% if status.message.message is not same as(null) %}
                                            <p class="accent bold">Vous avez répondu à la demande du staff.</p>
                                        {% endif %}
                                    {% else %}
                                        <p>Veuillez apporter une réponse.</p>
                                    {% endif %}
                                {% endif %}
                            </div>
                            <footer class="card__footer text-small">
                                <div class="text-truncate">
                                    {{ icon('event') }} {{ status.createdAt | date("d.m.Y à H:i") }}
                                </div>
                                <div>
                                    {{ icon('person') }} {{ status.createdBy }}
                                </div>
                            </footer>
                        </div>
                        {% if status.state.slug is same as("error") %}
                            {% if status.message is not same as(null) %}
                                {% if status.message.message is not same as(null) %}
                                    {% set message = status.message.message %}
                                    <div class="card full timeline-element">
                                        <div class="card__body stack">
                                            <h2 class="card__title">Réponse de {{ message.createdBy }} => {{ message.title }}</h2>
                                            <p>"{{ message.content | nl2br }}"</p>
                                        </div>
                                        <footer class="card__footer text-small">
                                            <div class="text-truncate">
                                                {{ icon('event') }} {{ message.createdAt | date("d.m.Y à H:i") }}
                                            </div>
                                            <div>
                                                {{ icon('person') }} {{ message.createdBy }}
                                            </div>
                                        </footer>
                                    </div>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/pages/order/conflicts_order.html.twig
{% extends 'base.html.twig' %}

{% set lightBody = true %}
{% set headerLight = true %}

{% block body %}
    <div class="page-header container">
        <div class="stack w100">
            <h1 class="h1">Equipment indisponible</h1>
        </div>
    </div>
    <div class="layout-sidebar py5" style="--gap: 5">
        <main class="stack-large">
            <div class="card p3">
                <p>Malheursement, l'équipement que vous avez séléctionné n'est pas disponible aux dates indiquées.</p>
            </div>
        </main>
        <aside class="stack">
            <div class="mb2">
                <div>
                    <h2 class="h5 mb2">
                        Équipement indisponible
                    </h2>
                    <div class="list-group">
                        {% for conflict in conflicts %}
                            <a href="#">{{ conflict[0].name }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </aside>
    </div>

{% endblock %}

templates/pages/order/equipment-order.html.twig
{% extends 'base.html.twig' %}

{% set lightBody = true %}
{% set headerContrast = true %}

{% block body %}
    <div class="page-header-accent container" style="padding-bottom: 200px">
        <h1 class="h1">{{ order.title }}</h1>
    </div>
    <div class="show-order-page">
        <div class="order-card">
            <div class="order-card__header">
                {{ include('components/_my-order_nav.html.twig') }}
            </div>
            <div class="order-card__body">
                <h2 class="order-card__title h2 mb4">Équipement demandé</h2>
                <div class="grid">
                    {% for equipment in order.equipment %}
                        {{ include('components/_equipment_card.html.twig') }}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/pages/order/error-order.html.twig
{% extends 'base.html.twig' %}

{% set lightBody = true %}
{% set headerContrast = true %}

{% block body %}
    <div class="page-header-accent container" style="padding-bottom: 200px">
        <h1 class="h1">{{ order.title }}</h1>
    </div>
    <div class="show-order-page">
        <div class="order-card">
            <div class="order-card__header">
                {{ include('components/_my-order_nav.html.twig') }}
            </div>
            <div class="order-card__body">
                <h2 class="order-card__title h2 mb2">Erreur sur votre commande</h2>
                <div class="support">
                    <div class="support-hero">
                        <p class="hero-infos mt4">
                            Voici la demande qui vous a été adressée</p>
                        <p class="hero-text">
                            "{{ messageRequest.orderState.comments }}"
                        </p>
                    </div>
                    <div class="support-hero">
                        <p class="hero-infos mt4">Votre réponse</p>
                        <p class="hero-text">
                            <span class="text-muted text-big">"</span>{{ messageRequest.message.content }}<span class="text-muted text-big">"</span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/pages/order/error-order_form.html.twig
{% extends 'base.html.twig' %}

{% set lightBody = true %}
{% set headerContrast = true %}

{% block body %}
    <div class="page-header-accent container" style="padding-bottom: 200px">
        <h1 class="h1">{{ order.title }}</h1>
    </div>
    <div class="show-order-page">
        <div class="order-card">
            <div class="order-card__header">
                {{ include('components/_my-order_nav.html.twig') }}
            </div>
            <div class="order-card__body">
                <h2 class="order-card__title h2 mb2">Une erreur est survenue</h2>
                <p class="order-card__paragraph hero-paragraph">Merci de répondre à la demande du staff dans les plus brefs délais.</p>
                <div class="support">
                    <div class="support-hero">
                        <p class="hero-infos mt4">
                            Voici la demande qui vous a été adressée</p>
                        <p class="hero-text">
                            "{{ messageRequest.orderState.comments }}"
                        </p>
                    </div>
                    <div class="stack-large mt4">
                        {{ form_start(form) }}
                        <section class="stack">
                            {{ form_row(form.title, {attr: {disabled: "disabled"}}) }}
                            {{ form_row(form.content) }}
                            <button class="btn-gradient mla">Répondre</button>
                        </section>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/pages/order/new.html.twig
{% extends 'base.html.twig' %}

{% set lightBody = true %}
{% set headerLight = true %}

{% block body %}
    <div class="page-header container">
        <div class="stack w100">
            <h1 class="h1">Informations générales</h1>
        </div>
    </div>
    <div class="layout-sidebar py5" style="--gap: 5">
        <main class="stack-large">
            {% if conflicts is defined %}
                <div class="mb2">
                    <alert-block
                            alert-title="Équipement(s) non diponible"
                            message="{% for conflict in conflicts %}{% if conflict.isConflict %}<p><strong class='bold'>{{ conflict.message }}</strong>{% else %}{{ conflict.message }}{% endif%} </p>{% endfor %}"
                            class="alert-warning"
                    ></alert-block>
                </div>
            {% endif %}
            {{ include('pages/order/_new_order_form.html.twig') }}
        </main>
        <aside class="stack">

        </aside>
    </div>


{% endblock %}

templates/pages/order/show-order.html.twig
{% extends 'base.html.twig' %}

{% set lightBody = true %}
{% set headerContrast = true %}

{% block body %}
    <div class="page-header-accent container" style="padding-bottom: 200px">
        <h1 class="h1">{{ order.title }}</h1>
    </div>
    <div class="show-order-page">
        <div class="order-card">
            <div class="order-card__header">
                {{ include('components/_my-order_nav.html.twig') }}
            </div>
            <div class="order-card__body">
                <h2 class="order-card__title h2 mb2">Résumé</h2>
                <p class="order-card__paragraph hero-paragraph">{{ order.description }}</p>
                <div class="hstack mt3" style="--gap: 6">

                    <div class="order-card__list">
                        <div class="card__list-icon">
                            {{ feather('hash') }}
                        </div>
                        <div>
                            <div class="card__list-label text-muted">
                                Numéro de commande
                            </div>
                            <div class="card__list-value">
                                {{ order.initialZeroId }}
                            </div>
                        </div>
                    </div>
                    <div class="order-card__list">
                        <div class="card__list-icon">
                            {{ feather('calendar') }}
                        </div>
                        <div>
                            <div class="card__list-label text-muted">
                                Dates
                            </div>
                            <div class="card__list-value">
                                {{ order.start | date("d.m.Y") }} -> {{ order.end | date("d.m.Y") }}
                            </div>
                        </div>
                    </div>

                    <div class="order-card__list">
                        <div class="card__list-icon">
                            {{ feather('user') }}
                        </div>
                        <div>
                            <div class="card__list-label text-muted">
                                Enseignant
                            </div>
                            <div class="card__list-value">
                                {{ order.teacher ?? 'Aucun enseignant' }}
                            </div>
                        </div>
                    </div>

                    <div class="order-card__list">
                        <div class="card__list-icon">
                            {{ feather('info') }}
                        </div>
                        <div>
                            <div class="card__list-label text-muted">
                                Statut
                            </div>
                            <div class="card__list-value">
                                {{ order.currentStatus.state.name }}
                            </div>
                        </div>
                    </div>

                    <div class="order-card__list">
                        <div class="card__list-icon">
                            {{ feather('clock') }}
                        </div>
                        <div>
                            <div class="card__list-label text-muted">
                                Dernière mise à jour
                            </div>
                            <div class="card__list-value">
                                le {{ order.currentStatus.createdAt | date("d.m.Y à H:i") }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}