src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Mime\Address;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{

    public const ROLES = [
        'ROLE_USER' => "Utilisateur",
        'ROLE_TEACHER' => "Enseignant",
        'ROLE_EDITOR' => "Editeur",
        'ROLE_ADMIN' => "Administrateur",
        'ROLE_WEBMASTER' => "Webmaster"
    ];

    public const STATUS = [
        "En attente de confirmation",
        "Activé",
        "Suspendu",
        "Désactivé"
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = ['ROLE_USER'];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $family_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $given_name;

    /**
     * @ORM\Column(type="integer")
     */
    private $status = 1;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    #[
        Assert\Regex("/\bcpnv.ch\b$/"),
        Assert\Email()
    ]
    private $email;

    /**
     * @ORM\ManyToOne(targetEntity=UserType::class, inversedBy="users")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="client")
     */
    private $orders;

    /**
     * @ORM\OneToOne(targetEntity=Teacher::class, mappedBy="userTeacher", cascade={"persist", "remove"})
     */
    private $teacher;

    /**
     * @ORM\OneToMany(targetEntity=Cart::class, mappedBy="user", orphanRemoval=true)
     */
    private $carts;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private $updatedBy;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="createdBy")
     */
    private $messages;

    public function __construct()
    {
        $this->setCreatedAt(new \DateTimeImmutable());
        $this->setUpdatedAt(new \DateTimeImmutable());
        $this->orders = new ArrayCollection();
        $this->carts = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFamilyName(): ?string
    {
        return $this->family_name;
    }

    public function setFamilyName(string $family_name): self
    {
        $this->family_name = $family_name;

        return $this;
    }

    public function getGivenName(): ?string
    {
        return $this->given_name;
    }

    public function setGivenName(string $given_name): self
    {
        $this->given_name = $given_name;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getType(): ?UserType
    {
        return $this->type;
    }

    public function setType(?UserType $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getStatusName()
    {
        return self::STATUS[$this->getStatus()];
    }

    public function getRoleString()
    {
        $string = "";
        $roles = new ArrayCollection($this->getRoles());
        $last = $roles->count() - 1;
        /** @var string[] $roles */
        foreach ($roles as $key => $role){
            if($key === $last){
                $string .= $role;
            }
            elseif($key === $last-1) {
                $string .= $role . " et ";
            }
            else{
                $string .= $role . ", ";
            }
        }
        return $string;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setClient($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getClient() === $this) {
                $order->setClient(null);
            }
        }

        return $this;
    }

    public function getFullname()
    {
        return $this->getGivenName() . " " . $this->getFamilyName();
    }

    public function __toString(): string
    {
        return $this->getFullname();
    }

    public function getRoleName()
    {
        $roles = new ArrayCollection($this->getRoles());
        return self::ROLES[$roles->last()];
    }

    public function getTeacher(): ?Teacher
    {
        return $this->teacher;
    }

    public function setTeacher(?Teacher $teacher): self
    {
        // unset the owning side of the relation if necessary
        if ($teacher === null && $this->teacher !== null) {
            $this->teacher->setUserTeacher(null);
        }

        // set the owning side of the relation if necessary
        if ($teacher !== null && $teacher->getUserTeacher() !== $this) {
            $teacher->setUserTeacher($this);
        }

        $this->teacher = $teacher;

        return $this;
    }

    public function isAdmin()
    {
        if (in_array("ROLE_WEBMASTER", $this->getRoles())) return true;
        elseif (in_array("ROLE_ADMIN", $this->getRoles())) return true;
        elseif (in_array("ROLE_EDITOR", $this->getRoles())) return true;
        else return false;
    }

    /**
     * @return Collection|Cart[]
     */
    public function getCarts(): Collection
    {
        return $this->carts;
    }

    public function addCart(Cart $cart): self
    {
        if (!$this->carts->contains($cart)) {
            $this->carts[] = $cart;
            $cart->setUser($this);
        }

        return $this;
    }

    public function getUpdatedBy(): ?self
    {
        return $this->updatedBy;
    }

    public function setUpdatedBy($updatedBy): self
    {
        $this->updatedBy = $updatedBy;

        return $this;
    }

    public function getEquipmentCart(Equipment $equipment): Cart|null
    {
        foreach ($this->getCarts() as $cart) {
            if($cart->getEquipment()->getId() === $equipment->getId()) return $cart;
        }
        return null;
    }

    public function isInCart(Equipment $equipment): bool
    {
        return !is_null($this->getEquipmentCart($equipment));
    }

    public function isCartEmpty(): bool
    {
        return $this->getCarts()->isEmpty();
    }

    public function getCartEquipment()
    {
        $output = new ArrayCollection();

        foreach ($this->getCarts() as $cart) {
            $output->add($cart->getEquipment());

templates/pages/cart.html.twig
{% extends 'base.html.twig' %}

{% set lightBody = true %}
{% set headerLight = true %}

{% block body %}
    <div class="page-header container">
        <div class="stack w100">
            <h1 class="h1">Mon panier</h1>
        </div>
    </div>
    <div class="layout-sidebar py5" style="--gap: 5">
        <main class="stack-large">
            <table class="table">
                <thead>
                    <tr>
                        <th>Équipement</th>
                        <th>Marque</th>
                        <th>Quantité</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cart in app.user.carts %}
                        {% set equipment = cart.equipment %}
                        <tr>
                            <td>{{ equipment.name }}</td>
                            <td>{{ equipment.brand }}</td>
                            <td>x{{ cart.quantity }}</td>
                            <td>
                                <form method="post" action="{{ path('user.cart.remove', { id: cart.id } ) }}" class="form-button">
                                   <button class="btn-small btn-danger">Retirer du panier</button>
                                </form>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="3">Votre panier est vide.</td>
                            <td>
                                <a href="{{ path('equipment') }}" class="btn-gradient">Découvrer l'équipement disponible</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </main>
        <aside class="stack">

            {% for section in content.sections %}
                <div class="mb2">
                    <div>
                        <h2 class="h5 mb2">
                            {{ section.name }}
                        </h2>
                        {% for paragraph in section.paragraphs %}
                            <p>{{ paragraph }}</p>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}

            <div>
                <div>
                    <p class="text-right">
                        {% if not app.user.isCartEmpty %}
                            <a href="{{ path('order.new') }}" class="btn-gradient">Commencer</a>
                        {% else %}
                            <a href="#" class="btn-gradient" disabled="disabled">Commencer</a>
                        {% endif %}
                    </p>
                </div>
            </div>
        </aside>
    </div>


{% endblock %}

templates/pages/equipment_show.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <div class="container">
        <div class="breadcrumb">
            <a href="{{ path('equipment') }}" class="link">Équipement</a> {{ icon('chevron_right') }} <a href="{{ path('equipment.type.show', {slug: equipment.type.slug}) }}" class="link">{{ equipment.type.name }}</a> {{ icon('chevron_right') }} <a href="{{ path('equipment.show', {id: equipment.id, slug: equipment.slug}) }}" class="link"><strong class="bold">{{ equipment.name }}</strong></a>
        </div>
    </div>
    <div class="equipment py5" style="--gap: 5">
        <main class="stack-large">
            <div class="card p3">
                <img src="{% if equipment.filename is not null %}{{ vich_uploader_asset(equipment) }}{% else %}{{ asset('images/default.png') }}{% endif %}" alt="{{ equipment.name }}">
            </div>
        </main>
        <aside class="stack">
            <div class="container mb3 flex equipment-control">
                <div>
                    <h1 class="h1">{{ equipment.name }}</h1>
                    <h3 class="hero-text">{{ equipment.type.name }}</h3>
                </div>
                {% if equipment.itemCount > 0 %}
                    {{ include('components/_cart_manage_btn.html.twig') }}
                {% else %}
                    <p class="text-muted">Ne peut pas être ajouté au panier</p>
                {% endif %}
            </div>
            <div class="card p3">
                <div class="mb2">
                    <div>
                        <h2 class="h5 mb2">Description</h2>
                        <p>{{ equipment.description }}</p>
                    </div>
                </div>
                <div class="mb2">
                    <div>
                        <h2 class="h5 mb2">Marque</h2>
                        <p>{{ equipment.brand.name }}</p>
                    </div>
                </div>
                <div class="mb2">
                    <div>
                        <h2 class="h5 mb2">Nombre</h2>
                        <p>{{ equipment.itemCount }}</p>
                    </div>
                </div>
                <div class="mb2">
                    <div>
                        <h2 class="h5 mb2">Catégorie(s)</h2>
                        <p>{{ equipment.categoriesCS }}</p>
                    </div>
                </div>
                <div class="mb2">
                    <div>
                        <h2 class="h5 mb2">
                            Informations
                        </h2>
                        <p><span class="bold">Ajouté le </span>{{ equipment.createdAt | date('d.m.Y à H:i') }}</p>
                        <p><span class="bold">Ajouté par </span>{{ equipment.createdBy.fullname }}</p>
                    </div>
                </div>
                <div>
                    <div>

                    </div>
                </div>
            </div>
        </aside>
    </div>
    <div class="equipment-page">
        <div class="container py5">
            <div class="stack">
                <div class="h2">Équipement similaire</div>
                <div class="grid">
                    {% for equipment in equipment.similar %}
                        {{ include('components/_equipment_card.html.twig') }}
                    {% else %}
                        <div class="card p3">
                            <h4 class="text-muted">Aucun équipement similaire trouvé.</h4>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/equipment_type_show.html.twig
{% extends 'base.html.twig' %}

{% set lightBody = true %}
{% set headerLight = true %}

{% block body %}
    <div class="page-header container type-header">
        <div class="stack w100">
            <h1 class="h1">{{ type.name }}</h1>
        </div>
    </div>
    <div class="layout-sidebar py5" style="--gap: 5">
        <main class="stack-large">
            <div class="hardware">
                {% for equipment in type.equipments %}
                    {{ include('components/_equipment_card.html.twig') }}
                {% else %}
                    <div class="card">
                        <div class="card__body stack">
                            <h2 class="card__title">
                                Aucun équipement n'est actuellment disponible.
                            </h2>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </main>
        <aside class="stack">
            <div class="mb2">
                <div>
                    <h2 class="h5 mb2">
                        Autres types d'équipement
                    </h2>
                    <div class="list-group">
                        {% for typeL in types %}
                            <a href="{{ path('equipment.type.show', {slug: typeL.slug}) }}">{{ typeL.name }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </aside>
    </div>


{% endblock %}

templates/pages/hardware.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <div class="container py5">
        <div class="hstack flex-end pb5">
            <div class="filters" data-controller="filter">
                <a href="#" class="filter-btn js-toggle-filter">
                    {{ feather('filter') }} Filtrer
                </a>
                {{ include('components/_filter.html.twig') }}
            </div>
        </div>
        <div class="hardware">
            <div class="equipment-hero">
                <h1 class="hero-title">
                    Tous <strong>l'équipement.</strong>
                </h1>
                <p class="hero-text">
                    Photo, vidéo, enregistrement audio, etc...<br>Tous ce dont vous avez besoins, se trouve ici.
                </p>
            </div>
            {% for equipment in equipments %}
                {{ include('components/_equipment_card.html.twig') }}
            {% else %}
                <div class="">
                    <div class="card__body stack">
                        <h2 class="card__title">
                            <span>Aucun n'équipement ne corresponds à vos critères</span>
                        </h2>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/pages/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container py5">
        <div class="hardware mb5">
            <div class="equipment-hero">
                <h1 class="hero-title">
                    Derniers <strong>équipements</strong> ajoutés.
                </h1>
                <p class="hero-text">
                    Voici les 5 derniers équipements ajoutés que vous pouvez commander dès à présent.
                </p>
            </div>
            {% for equipment in equipments %}
                {{ include('components/_equipment_card.html.twig') }}
            {% else %}
                <div class="">
                    <div class="card__body stack">
                        <h2 class="card__title">
                            <span>Aucun n'équipement ne corresponds à vos critères</span>
                        </h2>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    {% if not app.user.orders.empty %}
        {% set userOrder = app.user.orders.last %}
    <div class="equipment-page">
        <div class="container py5">
            <div class="stack">
                <div class="h2">Votre dernière commande</div>
                <div class="grid">
                    <div class="card">
                        <div class="card__body stack">
                            <h2 class="card__title">
                                <a href="{{ path('orders.user.show', {'id': userOrder.id}) }}">{{ userOrder.title }}</a>
                            </h2>
                            <p>
                                {{ userOrder.description | nl2br }}
                            </p>
                            <div class="flex flex-between">
                                <p>
                                    <strong class="bold">A partir du</strong> <br>
                                    {{ userOrder.start | date("d.m.Y") }}
                                </p>
                                <p>
                                    <strong class="bold">Jusqu'au</strong> <br>
                                    {{ userOrder.end | date("d.m.Y") }}
                                </p>
                            </div>
                        </div>
                        <footer class="card__footer text-small">
                            <div class="text-truncate" title="{{ userOrder.items.count }} objets commandés">
                                {{ icon('category') }} {{ userOrder.items.count }} objets commandés
                            </div>
                            <div title="Date de création de la commande">
                                {{ icon('event_available') }} {{ userOrder.createdAt | date("d.m.Y H:i") }}
                            </div>
                        </footer>
                        <div class="card__pills">
                            <div class="pill small pill-primary" style="color: #{{ userOrder.currentStatus.state.color }}">
                                {{ userOrder.currentStatus }}
                            </div>
                        </div>
                    </div>
                    {% for equipment in userOrder.equipment %}
                        {{ include('components/_equipment_card.html.twig') }}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% endif %}

{% endblock %}

templates/pages/my-orders.html.twig
{% extends 'base.html.twig' %}

{% set lightBody = true %}
{% set headerLight = true %}

{% block body %}
    <div class="page-header container">
        <h1 class="h1">Mes commandes</h1>
    </div>
    <div class="orders-page py3">
        <div class="orders-page__sidebar stack">
            <a href="{{ path('order.new') }}" class="btn-primary">Nouvelle commande</a>
            {#<ul class="orders-status">
                <li>
                    <a href="#">Afficher tout</a>
                </li>
                {% for state in states %}
                <li>
                    <a href="#"><span style="background-color: #{{ state.color }}"></span>{{ state.name }}</a>
                </li>
                {% endfor %}
            </ul>#}
        </div>
        <main class="orders-page__main stack">
            {% for order in orders %}
            <article class="order">
                <div class="order-col">
                    <div class="order-col__title">
                        <span>ID</span>
                    </div>
                    <div class="order-col__value">
                        <h5>{{ order.initialZeroId }}</h5>
                    </div>
                </div>
                <div class="order-col">
                    <div class="order-col__title">
                        <span>Nom du projet</span>
                    </div>
                    <div class="order-col__value">
                        <h5>{{ order.title }}</h5>
                    </div>
                </div>

                <div class="order-col">
                    <div class="order-col__title">
                        <span>Date de création</span>
                    </div>
                    <div class="order-col__value">
                        <h5>{{ order.createdAt | format_datetime('long', 'none') }}</h5>
                    </div>
                </div>

                <div class="order-col">
                    <div class="order-col__title">
                        <span>Bon de commande</span>
                    </div>
                    <div class="order-col__value">
                        <a href="{{ path('pdf.order.client', {'id': order.id}) }}" class="order-dl-btn" target="_blank">{{ feather('clipboard') }} Télécharger</a>
                    </div>
                </div>

                <div class="order-col">
                    <div class="order-col__title">
                        <span>Statut</span>
                    </div>
                    <div class="order-col__value">
                        <span class="pill small-round" style="color: #{{ order.currentStatus.state.color }}">{{ order.currentStatus }}</span>
                    </div>
                </div>

                <div class="order-col">
                    <a href="{{ path('orders.user.show', {id: order.id}) }}" class="order-btn">{{ feather('chevron-right') }}</a>
                </div>
            </article>
            {% endfor %}
        </main>
    </div>


{% endblock %}

templates/pages/profil.html.twig
{% extends 'base.html.twig' %}

{% set lightBody = true %}
{% set headerLight = true %}

{% block body %}
    <div class="page-header container">
        <div class="profil-header">
            <div class="profil-header__avatar">

            </div>
            <div class="profil-header__body">
                <h1 class="h1">Mon compte</h1>
                <p class="hstack" style="--gap: 1">
                    <span class="pill small pill-darkgrey">{{ app.user.roleName }}</span>
                    <small>
                        Inscrit depuis le {{ app.user.createdAt | date('d.m.Y') }}
                    </small>
                </p>
            </div>
        </div>
    </div>
    <div class="layout-sidebar py5" style="--gap: 5">
        <main class="stack-large">
            {{ form_start(form, {attr: {class: 'stack-large stacked'}}) }}
            <div class="stack">
                <h2 class="h3 align-center-y"><span class="material-icons-round">lock</span> Sécurité</h2>
                <div class="card p3 grid">
                    {{ form_row(form.password) }}
                </div>
                <div class="text-right">
                    <button type="submit" class="btn-primary">Mettre à jour</button>
                </div>
            </div>
            {{ form_end(form) }}
        </main>
        <aside class="stack">
            <div class="mb2">
                <div>
                    <h2 class="h5 mb2">
                        Changement de l'adresse e-mail
                    </h2>
                    <p>L'adresse e-mail ne peut être modifiée. Dans le cas où votre adresse venait à changer, veuillez vous adresser à un administrateur.</p>
                </div>
            </div>
            <div class="mb2">
                <div>
                    <h2 class="h5 mb2">
                        Votre adresse e-mail
                    </h2>
                    <p>{{ app.user.email }}</p>
                </div>
            </div>
            <div class="mb2">
                <div>
                    <h2 class="h5 mb2">
                        Informations
                    </h2>
                    <p><span class="bold">Créé le : </span>{{ app.user.createdAt | date('d.m.Y à H:i') }}</p>
                    <p><span class="bold">Modifié le : </span>{{ app.user.updatedAt | date('d.m.Y à H:i') }}</p>
                </div>
            </div>
        </aside>
    </div>


{% endblock %}

templates/pages/room-content.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container py5">
        <div class="support">
            <div class="support-hero">
                <h1 class="hero-title">
                    Salle Multimédia
                </h1>
                <p class="hero-infos">
                    Éléments disponible pour location
                </p>
            </div>
        </div>
        <div class="rooms">
            {% for room in rooms %}
                <section>
                    <img src="{{ vich_uploader_asset(room) }}" alt="{{ room }}">
                    <div>
                        <h2 class="h2">{{ room.name }}</h2>
                        <p>{{ room.description }}</p>
                        {{ include('components/_add_cart_room_btn.html.twig') }}
                    </div>
                </section>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/pages/support.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container py5">
    <div class="support">
        <div class="support-hero">
            <h1 class="hero-title">
                Informations
            </h1>
            <p class="hero-infos">
                {{ content.updatedAt | format_datetime('long', 'none') }} • {{ content.updatedBy }} • Espace Multimédia
            </p>
        </div>
        {% for section in content.sections %}
            <section>
                <h2 class="h2">{{ section.name }}</h2>
                {% for p in section.paragraphs %}
                    <p>{{ p.text }}</p>
                {% endfor %}
            </section>
        {% endfor %}
    </div>
</div>
{% endblock %}