src/Entity/Item.php
<?php

namespace App\Entity;

use App\Repository\ItemRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=ItemRepository::class)
 */
class Item
{

    public const STATES = [
        0 => "Neuf",
        1 => "En bon état",
        2 => "Dommage esthétique",
        3 => "Dommage de fonctionnement",
        4 => "Innutilisable",
        5 => "En réparation",
        6 => "Épave"
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tag;

    /**
     * @ORM\Column(type="integer")
     */
    private $state;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $createdBy;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $updatedBy;

    /**
     * @ORM\ManyToOne(targetEntity=Equipment::class, inversedBy="items")
     * @ORM\JoinColumn(nullable=false)
     */
    private $equipment;

    /**
     * @ORM\ManyToMany(targetEntity=Order::class, mappedBy="items")
     */
    private $orders;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=UsedItem::class, mappedBy="item")
     */
    private $usedItems;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
        $this->setUpdatedAt(new \DateTimeImmutable());
        $this->setCreatedAt(new \DateTimeImmutable());
        $this->usedItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTag(): ?string
    {
        return $this->tag;
    }

    public function setTag(string $tag): self
    {
        $this->tag = $tag;

        return $this;
    }

    public function getState(): ?int
    {
        return $this->state;
    }

    public function getStateText(): string
    {
        return self::STATES[$this->state];
    }

    public function setState(int $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCreatedBy(): User|UserInterface
    {
        return $this->createdBy;
    }

    public function setCreatedBy(User|UserInterface $createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    public function getUpdatedBy(): User|UserInterface
    {
        return $this->updatedBy;
    }

    public function setUpdatedBy(User|UserInterface $updatedBy): self
    {
        $this->updatedBy = $updatedBy;

        return $this;
    }

    public function getEquipment(): ?Equipment
    {
        return $this->equipment;
    }

    public function setEquipment(?Equipment $equipment): self
    {
        $this->equipment = $equipment;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getEquipment().'#'.$this->getTag();
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->addItem($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            $order->removeItem($this);
        }

        return $this;
    }

    public function getComments(): ?string
    {
        return $this->comments;
    }

    public function setComments(?string $comments): self
    {
        $this->comments = $comments;

        return $this;
    }

    /**
     * @return Collection|UsedItem[]
     */
    public function getUsedItems(): Collection
    {
        return $this->usedItems;
    }

    public function addUsedItem(UsedItem $usedItem): self
    {
        if (!$this->usedItems->contains($usedItem)) {
            $this->usedItems[] = $usedItem;
            $usedItem->setItem($this);
        }

        return $this;
    }

    public function removeUsedItem(UsedItem $usedItem): self
    {
        if ($this->usedItems->removeElement($usedItem)) {
            // set the owning side to null (unless already changed)
            if ($usedItem->getItem() === $this) {
                $usedItem->setItem(null);
            }
        }

        return $this;
    }

}

src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="orders")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\Column(type="date_immutable")
     * @Assert\GreaterThan("today")
     */
    private $start;

    /**
     * @ORM\Column(type="date_immutable")
     * @Assert\GreaterThanOrEqual(propertyPath="start")
     */
    private $end;

    /**
     * @ORM\ManyToMany(targetEntity=Item::class, inversedBy="orders", orphanRemoval=false)
     */
    private $items;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity=OrderState::class, mappedBy="order", cascade={"persist"}, orphanRemoval=true)
     */
    private $orderStates;

    /**
     * @ORM\OneToMany(targetEntity=OrderDocument::class, mappedBy="document_order", orphanRemoval=true)
     */
    private $documents;

    /**
     * @ORM\ManyToOne(targetEntity=Teacher::class, inversedBy="orders")
     */
    private $teacher;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\ManyToMany(targetEntity=Equipment::class, inversedBy="orders")
     */
    private $equipment;

    /**
     * @ORM\OneToMany(targetEntity=UsedItem::class, mappedBy="ordr")
     */
    private $usedItems;


    public function __construct()
    {
        $this->items = new ArrayCollection();
        $this->orderStates = new ArrayCollection();
        $this->documents = new ArrayCollection();
        $this->setCreatedAt(new \DateTimeImmutable());
        $this->equipment = new ArrayCollection();
        $this->usedItems = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClient(): User|UserInterface
    {
        return $this->client;
    }

    public function setClient(User|UserInterface $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getStart(): ?DateTimeImmutable
    {
        return $this->start;
    }

    public function setStart(\DateTime $start): self
    {
        $this->start = DateTimeImmutable::createFromMutable($start);

        return $this;
    }

    public function getEnd(): ?DateTimeImmutable
    {
        return $this->end;
    }

    public function setEnd(\DateTime $end): self
    {

        $this->end = DateTimeImmutable::createFromMutable($end);

        return $this;
    }

    /**
     * @return Collection|Item[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(Item $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
        }

        return $this;
    }

    public function getItemsCount(): int
    {
        return $this->items->count();
    }

    public function removeItem(Item $item): self
    {
        $this->items->removeElement($item);

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|OrderState[]
     */
    public function getOrderStates(): Collection
    {
        return $this->orderStates;
    }

    public function addOrderState(OrderState $orderState): self
    {
        if (!$this->orderStates->contains($orderState)) {
            $this->orderStates[] = $orderState;
            $orderState->setOrder($this);
        }

        return $this;
    }

    public function removeOrderState(OrderState $orderState): self
    {
        if ($this->orderStates->removeElement($orderState)) {
            // set the owning side to null (unless already changed)
            if ($orderState->getOrder() === $this) {
                $orderState->setOrder(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|OrderDocument[]
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    public function addDocument(OrderDocument $document): self
    {
        if (!$this->documents->contains($document)) {
            $this->documents[] = $document;
            $document->setDocumentOrder($this);
        }

        return $this;
    }

    public function removeDocument(OrderDocument $document): self
    {
        if ($this->documents->removeElement($document)) {
            // set the owning side to null (unless already changed)
            if ($document->getDocumentOrder() === $this) {
                $document->setDocumentOrder(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getClient() . " - " . $this->getCreatedAt()->format("d.m.Y H:i");
    }

    public function getTeacher(): ?Teacher
    {
        return $this->teacher;
    }

    public function setTeacher(?Teacher $teacher): self
    {
        $this->teacher = $teacher;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return Collection|Equipment[]
     */
    public function getEquipment(): Collection
    {
        return $this->equipment;
    }

    /**
     * @param Equipment[]|Collection $equipments
     * @return Order
     */
    public function setEquipment(mixed $equipments)
    {
        foreach ($equipments as $equipment) {
            $this->addEquipment($equipment);
        }
        return $this;
    }

    public function addEquipment(Equipment $equipment): self
    {
        if (!$this->equipment->contains($equipment)) {
            $this->equipment[] = $equipment;
        }

        return $this;
    }

    public function removeEquipment(Equipment $equipment): self
    {
        $this->equipment->removeElement($equipment);

        return $this;
    }

    public function isConfilct(DateTimeImmutable $start, DateTimeImmutable $end)
    {
        $thisStart = $this->getStart()->getTimestamp();
        $thisEnd = $this->getEnd()->getTimestamp();
        return ($start->getTimestamp() >= $thisStart && $end->getTimestamp() <= $thisEnd) || ($start->getTimestamp() <= $thisEnd && $start->getTimestamp() >= $thisStart) || ($end->getTimestamp() >= $thisStart && $end->getTimestamp() <= $thisEnd) || ($start->getTimestamp() <= $thisStart && $end->getTimestamp() >= $thisEnd);
    }

    public function getInitialZeroId(): string
    {
        $base = "0000";
        $base = substr($base, -0, -strlen((string)$this->getId()));
        $base .= $this->getId();
        return $base;
    }

    public function getCurrentStatus(): OrderState {
        return $this->getOrderStates()->last();
    }

    /**
     * @return Collection|UsedItem[]
     */
    public function getUsedItems(): Collection
    {
        return $this->usedItems;
    }

    public function addUsedItem(UsedItem $usedItem): self
    {
        if (!$this->usedItems->contains($usedItem)) {
            $this->usedItems[] = $usedItem;
            $usedItem->setOrdr($this);
        }

        return $this;
    }

    public function removeUsedItem(UsedItem $usedItem): self
    {
        if ($this->usedItems->removeElement($usedItem)) {
            // set the owning side to null (unless already changed)
            if ($usedItem->getOrdr() === $this) {
                $usedItem->setOrdr(null);
            }
        }

        return $this;
    }

    public function getErrorState(): ?OrderState
    {
        foreach ($this->getOrderStates() as $orderState) {
            if($orderState->getState()->getSlug() === "error") return $orderState;
        }
        return null;
    }
}

src/Controller/PdfController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


#[Route("/pdf", name: "pdf.")]
class PdfController extends AbstractController
{

    #[Route("/order/admin/{id}", name: "order.admin")]
    public function orderAdmin(Order $order): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        $equipments = new ArrayCollection([]);

        foreach ($order->getEquipment() as $equipment) {
            $items = new ArrayCollection([]);
            foreach ($order->getItems() as $item) {
                if($equipment->getId() === $item->getEquipment()->getId()) {
                    $items[] = $item;
                }
            }
            $equipments->add([
                'items' => $items,
                'equipment' => $equipment
            ]);
        }

        return $this->render('pdf/bdc.html.twig', [
            'order' => $order,
            'equipments' => $equipments
        ]);
    }

    #[Route("/order/client/{id}", name: "order.client")]
    public function orderClient(Order $order): Response
    {
        $equipments = new ArrayCollection([]);

        foreach ($order->getEquipment() as $equipment) {
            $items = new ArrayCollection([]);
            foreach ($order->getItems() as $item) {
                if($equipment->getId() === $item->getEquipment()->getId()) {
                    $items[] = $item;
                }
            }
            $equipments->add([
                'items' => $items,
                'equipment' => $equipment
            ]);
        }

        return $this->render('pdf/bdc_client.html.twig', [
            'order' => $order,
            'equipments' => $equipments
        ]);
    }
}

templates/pdf/bdc.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Epilogue:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Poppins:wght@100;200;300;400;500;600;700;800;900&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet">

    {% block stylesheets %}
        {{ encore_entry_link_tags('print') }}
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('print') }}
    {% endblock %}

    <title>Bon de livraison</title>
</head>
<body>
    <div class="page-wraper">
        <header>
            <div>
                <h1>Bon de commande</h1>
                <h3 class="font-mono"><span class="bold">#</span>{{ order.initialZeroId }}</h3>
            </div>
            <div class="dates">
                <p class="date">Dates : {{ order.start | date("d.m.Y") }}</p>
                <p>-> <span class="date">{{ order.end | date("d.m.Y") }}</span></p>
            </div>
        </header>

        <div class="details">
            <div>
                <div class="d-title">Émis par</div>
                <div class="d-value">Espace Multimédia</div>
            </div>

            <div>
                <div class="d-title">À l'attention de</div>
                <div class="d-value">{{ order.client }}</div>
            </div>

            <div>
                <div class="d-title">Informations</div>
                <div class="d-table">
                    <p>
                        <span class="dt-title">Nom du compte</span><br>
                        <span class="dt-value">{{ order.client }}</span>
                    </p>
                    <p>
                        <span class="dt-title">Adresse e-mail</span><br>
                        <span class="dt-value">{{ order.client.email }}</span>
                    </p>
                    <p>
                        <span class="dt-title">Commande passée le</span><br>
                        <span class="dt-value">{{ order.createdAt | date("d.m.Y à H:i") }}</span>
                    </p>
                </div>
            </div>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>Quantité</th>
                    <th class="col-name">Nom</th>
                    <th>Staff</th>
                    <th>Client</th>
                </tr>
            </thead>
            <tbody>
                {% for equipment in equipments %}
                <tr>
                    <td class="quantity">
                        <div class="quantity-value font-mono">{{ equipment.items.count }}</div>
                    </td>
                    <td>
                        <div class="font-mono">
                            <p class="bold equipment-title">{{ equipment.equipment }}</p>
                            {% for item in equipment.items %}
                                <p class="item-tag">{{ item.tag }}</p>
                            {% endfor %}
                        </div>
                    </td>
                    <td colspan="2">
                        <div class="sign-form">
                            <div class="form-title">Mise à disposition</div>

                            <div class="input-group">
                                <div class="input-control">
                                    <div class="label">
                                        <span>Signature</span>
                                        <span>Date</span>
                                    </div>
                                    <div class="input">/</div>
                                </div>

                                <div class="input-control">
                                    <div class="label">
                                        <span>Signature</span>
                                        <span>Date</span>
                                    </div>
                                    <div class="input">/</div>
                                </div>
                            </div>


                            <div class="form-title">Remise</div>
                            <div class="input-group">
                                <div class="input-control">
                                    <div class="label">
                                        <span>Signature</span>
                                        <span>Date</span>
                                    </div>
                                    <div class="input">/</div>
                                </div>

                                <div class="input-control">
                                    <div class="label">
                                        <span>Signature</span>
                                        <span>Date</span>
                                    </div>
                                    <div class="input">/</div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

templates/pdf/bdc_1.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Commande N°{{ order.initialZeroId }}</title>
    <style>
        * {
            font-family: "Ubuntu", sans-serif;
            padding: 0;
            margin: 0;
        }

        body{
            display: flex;
            flex-direction: column;
            padding: 50px;
        }
        header {
            width: 100%;
            margin-bottom: 20px;
        }

        header table{
            width: 100%;
        }

        header .title {
            text-align: right;
        }
        header .title h1 {
            font-size: 30px;
        }

        header .logo img{
            height: 70px;
        }

        header .title h4{
            color: #A3A3A3;
            font-size: 20px;
        }

        main section {
            margin-top: 50px;
            width: 100%;
        }

        main section h2{
            font-size: 20px;
            margin-bottom: 20px;
        }

        main table{
            width: 100%;
            border-collapse: collapse;
            border: none;
        }

        main table th{
            color: #A2A2A2;
            font-weight: 400;
            font-family: "Ubuntu", sans-serif;
            text-align: left;
        }

        main table tr > *{
            padding: 5px 0px;
        }

        main table td{
            color: #000000;
            font-weight: bold;
        }

        main table td:last-child{
            text-align: right;
        }

        .field{
            width: 125px;
            padding: 3px 5px;
            font-size: 20px;
            color: #ffe9ea;
            background-color: #ffe9ea;
            position: relative;
            border-bottom: 1px solid #f14949;
        }

        .field-big{
            width: 165px;
            padding: 3px 5px;
            font-size: 30px;
            color: #ffe9ea;
            background-color: #ffe9ea;
        }

        .field .label {
            position: absolute;
            top: 2px;
            left: 2px;
            font-size: 8px;
            color: #ff8080;
        }

    </style>
</head>
<body>
    <header>
        <table>
            <tr>
                <td>
                    <div class="logo">
                        {{ logo | raw }}
                    </div>
                </td>
                <td>
                    <div class="title">
                        <h1>Bon de commande</h1>
                        <h4>{{ order.initialZeroId }}</h4>
                    </div>
                </td>
            </tr>
        </table>
    </header>
    <main>
        <section>
            <h2>Détails de la commande</h2>
            <table>
                <tr>
                    <th>Client</th>
                    <td>{{ order.client }}</td>
                    <th>N° de commande</th>
                    <td>{{ order.initialZeroId }}</td>
                </tr>
                <tr>
                    <th>Enseignant</th>
                    <td>{{ order.teacher }}</td>
                    <th>Date de commande</th>
                    <td>{{ order.createdAt | date("d.m.Y") }}</td>
                </tr>
                <tr>
                    <th>Projet</th>
                    <td>{{ order.title }}</td>
                    <th>Remis le</th>
                    <td>{{ order.orderStates.last.createdAt | date("d.m.Y à H:i") }}</td>
                </tr>
                <tr>
                    <th>Début</th>
                    <td>{{ order.start | date("d.m.Y") }}</td>
                    <th>Remis par</th>
                    <td>{{ order.orderStates.last.createdBy }}</td>
                </tr>
                <tr>
                    <th>Fin</th>
                    <td>{{ order.end | date("d.m.Y") }}</td>
                    <th>Date de récupération</th>
                    <td>_______________</td>
                </tr>
            </table>
        </section>
        <section>
            <h2>Équipements</h2>
            <table>
                <tr>
                    <th>Nom</th>
                    <th>Marque</th>
                    <th>État</th>
                    <th>Remarques</th>
                    <th>Signature client</th>
                    <th>Signature staff</th>
                    <th>Tag</th>
                </tr>
                {% for item in order.items %}
                <tr>
                    <td>{{ item.equipment.name }}</td>
                    <th>{{ item.equipment.brand }}</th>
                    <th>{{ item.stateText }}</th>
                    <td colspan="4">{{ item.tag }}</td>
                </tr>
                <tr>
                    <td colspan="3"></td>
                    <th style="padding-right: 5px"><div class="field">placeholder</div></th>
                    <th style="padding-right: 5px"><div class="field">placeholder</div></th>
                    <th style="padding-right: 5px"><div class="field">placeholder</div></th>
                    <td></td>
                </tr>
                <tr style="border-bottom: 1px solid #000000">
                    <td colspan="3"></td>
                    <th><div class="field">placeholder</div></th>
                    <td colspan="2"></td>
                </tr>
                {% endfor %}
            </table>
        </section>
        <section>
            <h2>Signatures</h2>

            <h4>À signer au début</h4>

            <table class="signtable" style="border-bottom: 1px solid #dcdcdc">
                <tr>
                    <td>
                        <div>{{ app.user }}</div>
                        <div style="font-size: 13px; color: #6d6d6d; font-family: Inter, sans-serif">Staff Espace Multimédia</div>
                        <div class="field-big">placeholder</div>
                        <div class="field" style="margin-top: 5px"><span class="label">Date</span> placeholder</div>
                    </td>
                    <td style="width: 50%"></td>
                    <td style="display: flex; justify-content: flex-end">
                        <div>{{ order.client }}</div>
                        <div style="font-size: 13px; color: #6d6d6d; font-family: Inter, sans-serif">Client</div>
                        <br>
                        <div class="field-big">placeholder</div>
                        <div class="field" style="margin-top: 5px"><span class="label">Date</span> placeholder</div>
                    </td>
                </tr>
            </table>

            <h4 style="margin-top: 20px">À signer à la fin </h4>
            <table class="signtable">
                <tr>
                    <td {# style="padding-bottom: 30px; border-bottom: 1px solid #313131" #}>
                        <div><div class="field"><span class="label">Nom & prénom</span> placeholder</div></div>
                        <div style="font-size: 13px; color: #6d6d6d; font-family: Inter, sans-serif">Enseignant</div>
                        <div class="field-big">placeholder</div>
                        <div class="field" style="margin-top: 5px"><span class="label">Date</span> placeholder</div>
                    </td>
                    <td style="width: 50%"></td>
                    <td style="display: flex; justify-content: flex-end">
                        <div>{{ order.client }}</div>
                        <div style="font-size: 13px; color: #6d6d6d; font-family: Inter, sans-serif">Client</div>
                        <br>
                        <div class="field-big">placeholder</div>
                        <div class="field" style="margin-top: 5px"><span class="label">Date</span> placeholder</div>
                    </td>
                </tr>
            </table>
        </section>
    </main>
</body>
</html>