src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="orders")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\Column(type="date_immutable")
     * @Assert\GreaterThan("today")
     */
    private $start;

    /**
     * @ORM\Column(type="date_immutable")
     * @Assert\GreaterThanOrEqual(propertyPath="start")
     */
    private $end;

    /**
     * @ORM\ManyToMany(targetEntity=Item::class, inversedBy="orders", orphanRemoval=false)
     */
    private $items;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity=OrderState::class, mappedBy="order", cascade={"persist"}, orphanRemoval=true)
     */
    private $orderStates;

    /**
     * @ORM\OneToMany(targetEntity=OrderDocument::class, mappedBy="document_order", orphanRemoval=true)
     */
    private $documents;

    /**
     * @ORM\ManyToOne(targetEntity=Teacher::class, inversedBy="orders")
     */
    private $teacher;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\ManyToMany(targetEntity=Equipment::class, inversedBy="orders")
     */
    private $equipment;

    /**
     * @ORM\OneToMany(targetEntity=UsedItem::class, mappedBy="ordr")
     */
    private $usedItems;


    public function __construct()
    {
        $this->items = new ArrayCollection();
        $this->orderStates = new ArrayCollection();
        $this->documents = new ArrayCollection();
        $this->setCreatedAt(new \DateTimeImmutable());
        $this->equipment = new ArrayCollection();
        $this->usedItems = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClient(): User|UserInterface
    {
        return $this->client;
    }

    public function setClient(User|UserInterface $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getStart(): ?DateTimeImmutable
    {
        return $this->start;
    }

    public function setStart(\DateTime $start): self
    {
        $this->start = DateTimeImmutable::createFromMutable($start);

        return $this;
    }

    public function getEnd(): ?DateTimeImmutable
    {
        return $this->end;
    }

    public function setEnd(\DateTime $end): self
    {

        $this->end = DateTimeImmutable::createFromMutable($end);

        return $this;
    }

    /**
     * @return Collection|Item[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(Item $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
        }

        return $this;
    }

    public function getItemsCount(): int
    {
        return $this->items->count();
    }

    public function removeItem(Item $item): self
    {
        $this->items->removeElement($item);

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|OrderState[]
     */
    public function getOrderStates(): Collection
    {
        return $this->orderStates;
    }

    public function addOrderState(OrderState $orderState): self
    {
        if (!$this->orderStates->contains($orderState)) {
            $this->orderStates[] = $orderState;
            $orderState->setOrder($this);
        }

        return $this;
    }

    public function removeOrderState(OrderState $orderState): self
    {
        if ($this->orderStates->removeElement($orderState)) {
            // set the owning side to null (unless already changed)
            if ($orderState->getOrder() === $this) {
                $orderState->setOrder(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|OrderDocument[]
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    public function addDocument(OrderDocument $document): self
    {
        if (!$this->documents->contains($document)) {
            $this->documents[] = $document;
            $document->setDocumentOrder($this);
        }

        return $this;
    }

    public function removeDocument(OrderDocument $document): self
    {
        if ($this->documents->removeElement($document)) {
            // set the owning side to null (unless already changed)
            if ($document->getDocumentOrder() === $this) {
                $document->setDocumentOrder(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getClient() . " - " . $this->getCreatedAt()->format("d.m.Y H:i");
    }

    public function getTeacher(): ?Teacher
    {
        return $this->teacher;
    }

    public function setTeacher(?Teacher $teacher): self
    {
        $this->teacher = $teacher;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return Collection|Equipment[]
     */
    public function getEquipment(): Collection
    {
        return $this->equipment;
    }

    /**
     * @param Equipment[]|Collection $equipments
     * @return Order
     */
    public function setEquipment(mixed $equipments)
    {
        foreach ($equipments as $equipment) {
            $this->addEquipment($equipment);
        }
        return $this;
    }

    public function addEquipment(Equipment $equipment): self
    {
        if (!$this->equipment->contains($equipment)) {
            $this->equipment[] = $equipment;
        }

        return $this;
    }

    public function removeEquipment(Equipment $equipment): self
    {
        $this->equipment->removeElement($equipment);

        return $this;
    }

    public function isConfilct(DateTimeImmutable $start, DateTimeImmutable $end)
    {
        $thisStart = $this->getStart()->getTimestamp();
        $thisEnd = $this->getEnd()->getTimestamp();
        return ($start->getTimestamp() >= $thisStart && $end->getTimestamp() <= $thisEnd) || ($start->getTimestamp() <= $thisEnd && $start->getTimestamp() >= $thisStart) || ($end->getTimestamp() >= $thisStart && $end->getTimestamp() <= $thisEnd) || ($start->getTimestamp() <= $thisStart && $end->getTimestamp() >= $thisEnd);
    }

    public function getInitialZeroId(): string
    {
        $base = "0000";
        $base = substr($base, -0, -strlen((string)$this->getId()));
        $base .= $this->getId();
        return $base;
    }

    public function getCurrentStatus(): OrderState {
        return $this->getOrderStates()->last();
    }

    /**
     * @return Collection|UsedItem[]
     */
    public function getUsedItems(): Collection
    {
        return $this->usedItems;
    }

    public function addUsedItem(UsedItem $usedItem): self
    {
        if (!$this->usedItems->contains($usedItem)) {
            $this->usedItems[] = $usedItem;
            $usedItem->setOrdr($this);
        }

        return $this;
    }

    public function removeUsedItem(UsedItem $usedItem): self
    {
        if ($this->usedItems->removeElement($usedItem)) {
            // set the owning side to null (unless already changed)
            if ($usedItem->getOrdr() === $this) {
                $usedItem->setOrdr(null);
            }
        }

        return $this;
    }

    public function getErrorState(): ?OrderState
    {
        foreach ($this->getOrderStates() as $orderState) {
            if($orderState->getState()->getSlug() === "error") return $orderState;
        }
        return null;
    }
}

templates/components/_add_cart_room_btn.html.twig
{% if app.user.inCart(room) %}
    <a href="{{ path('room.toggle', {'id': room.id}) }}" class="btn-gradient btn-big">{{ icon('remove_shopping_cart') }}Retirer du panier</a>
{% else %}
    <a href="{{ path('room.toggle', {'id': room.id}) }}" class="btn-gradient btn-big">{{ icon('shopping_cart') }}Ajouter au panier</a>
{% endif %}

templates/components/_alert.html.twig
<alert-block message="{{ text }}" class="alert-warning{% if isClose is defined %} closed{% endif %}">
    <div class="alert-header">
        <div class="alert__title">
            {{ icon('warning') }}
            <span class="alert__title-title">{{ title }}</span>
        </div>
        <div class="alert-minimize">
            <a href="#" class="alert__minimize-btn">
                {{ feather('chevron-down') }}
            </a>
        </div>
    </div>
    <div class="alert-body">
        <p>{{ text }}</p>
    </div>
</alert-block>

templates/components/_cart.html.twig
<a href="#" class="cart-btn js-cart-toggle" {% if not app.user.carts.empty %}data-is-filled{% endif %}>{{ icon('shopping_cart') }}</a>
<div class="cart js-cart-container">
    <div>
        <div class="cart__header">
            <div class="cart__title">
                <span>Mon panier</span>
            </div>
        </div>
        <div class="cart__body">
            {% if app.user.carts.empty %}
                <div class="cart-item">Aucun équipement n'a été ajouté au panier !</div>
                <div class="cart-item text-center">
                    <a href="{{ path('equipment') }}" class="btn-gradient">Découvrer l'équipement disponible</a>
                </div>
            {% else %}
                {% for cart in app.user.carts %}
                    <a href="{{ path('equipment.show', {id: cart.equipment.id, slug: cart.equipment.slug}) }}" class="cart-item">
                        <div>
                            {{ cart.equipment.categoriesCS }} <br>
                            <strong>{{ cart.equipment.name }}</strong>
                            <strong> ({{ cart.equipment.type.name }})</strong>
                        </div>
                        <small class="text-muted">{{ cart.equipment.brand.name }}</small>
                    </a>
                {% endfor %}
                <div class="cart-item text-center">
                    <a href="{{ path('user.cart') }}" class="btn-gradient">Afficher le panier</a>
                </div>
            {% endif %}
        </div>
    </div>
</div>

templates/components/_cart_manage_btn.html.twig
{% if app.user.inCart(equipment) %}
    {{ form_start(cartForm, { attr: { class: "form-button" }}) }}
        {{ form_row(cartForm.quantity, {attr: {style: "display: none;"}}) }}
        <button class="btn-gradient btn-big">{{ icon('remove_shopping_cart') }}Retirer du panier</button>
    {{ form_end(cartForm) }}
{% else %}
    {{ form_start(cartForm, { attr: { class: "form-button cart-form" }}) }}
        {{ form_row(cartForm.quantity) }}
        <button class="btn-gradient btn-big">{{ icon('shopping_cart') }}Ajouter au panier</button>
    {{ form_end(cartForm) }}
{% endif %}
{#
{% if app.user.cart.contains(equipment) %}
    <form action="{{ path("user.cart.remove", {id: equipment.id}) }}" method="POST" class="form-button">
        <button class="btn-gradient btn-big">{{ icon('remove_shopping_cart') }}Retirer du panier</button>
    </form>
{% else %}
    <form action="{{ path("user.cart.add", {id: equipment.id}) }}" method="POST" class="form-button">
        <button class="btn-gradient btn-big">{{ icon('shopping_cart') }}Ajouter au panier</button>
    </form>
{% endif %}#}

templates/components/_equipment_action_card.html.twig
<div class="card">
    <div class="card__body stack">
        <h2 class="card__title">
            <a href="#">{{ equipment.name }}</a>
        </h2>
        <div class="card__image">
            <img src="{{ vich_uploader_asset(equipment) }}" alt="">
        </div>
    </div>
    <footer class="card__footer text-small">
        <div class="text-truncate">
            {{ icon('bookmark_border') }} {{ equipment.categoriesCS }}
        </div>
        <div>
            {{ icon('copyright') }} {{ equipment.brand.name }}
        </div>
    </footer>
    <div class="card__actions">
        <form action="{{ path("user.cart.remove", {id: equipment.id}) }}" method="POST" class="form-button">
            <button class="card__action-btn btn-primary-outlined btn-small">{{ icon('remove_shopping_cart') }}</button>
        </form>
    </div>
    <a class="card__link" href="{{ path('equipment.show', {id: equipment.id, slug: equipment.slug}) }}"></a>
</div>

templates/components/_equipment_card.html.twig
<div class="card">
    <div class="card__body stack">
        <h2 class="card__title">
            <a href="{{ path('equipment.show', {id: equipment.id, slug: equipment.slug}) }}">{{ equipment.name }}</a>
        </h2>
        <div class="card__image">
            <img src="{% if equipment.filename is not null %}{{ vich_uploader_asset(equipment) }}{% else %}{{ asset('images/default.png') }}{% endif %}" alt="">
        </div>
    </div>
    <footer class="card__footer text-small">
        <div class="text-truncate">
            {{ icon('bookmark_border') }} {{ equipment.categoriesCS }}
        </div>
        <div>
            {{ icon('copyright') }} {{ equipment.brand.name }}
        </div>
    </footer>
    <div class="card__pills">
        <div class="pill small pill-primary">
            {{ equipment.type.name }}
        </div>
    </div>
    <a class="card__link" href="{{ path('equipment.show', {id: equipment.id, slug: equipment.slug}) }}"></a>
    {% if app.user.isInCart(equipment) %}<div class="inCart"><i data-feather="check"></i></div>{% endif %}
</div>

templates/components/_equipment_card_home.html.twig
<div class="card">
    <div class="card__body stack">
        <h2 class="card__title">
            <a href="{{ path('equipment.show', {id: equipment.id, slug: equipment.slug}) }}">{{ equipment.name }}</a>
        </h2>
        <div class="card__image">
            <img src="{% if equipment.filename is not null %}{{ vich_uploader_asset(equipment) }}{% else %}{{ asset('images/default.png') }}{% endif %}" alt="">
        </div>
    </div>
    <footer class="card__footer text-small">
        <div class="text-truncate">
            {{ icon('bookmark_border') }} {{ equipment.categoriesCS }}
        </div>
        <div>
            {{ icon('copyright') }} {{ equipment.brand.name }}
        </div>
    </footer>
    <div class="card__pills">
        <div class="pill" style="color: #ff7b1e">
            Nouveau
        </div>
    </div>
    <a class="card__link" href="{{ path('equipment.show', {id: equipment.id, slug: equipment.slug}) }}"></a>
    {% if app.user.isInCart(equipment) %}<div class="inCart"><i data-feather="check"></i></div>{% endif %}
</div>

templates/components/_filter.html.twig
<div class="filter">
    <div class="filter__header">
        <h4 class="h3">Filtres</h4>
    </div>
    {{ form_start(form, {attr: { class: 'filter__form' }}) }}
        {{ form_row(form.categories) }}
        {{ form_row(form.brands) }}
        {{ form_row(form.types) }}
        <div class="hstack flex-end">
            <button class="btn-primary-outlined">Appliquer</button>
        </div>
    {{ form_end(form) }}
</div>

templates/components/_header-nav.html.twig
<nav class="header {% if lightBody is defined %}header-light{% endif %}" style="--color-light: #8491c7;">
    <ul class="header-nav">
        <li class="header__home">
            <a href="{{ path('app.home') }}" {{ menu_active('home') }} title="Accueil">
                {{ icon('home') }}
            </a>
        </li>
        <li><a href="{{ path('equipment') }}" {{ menu_active('hardware') }}>{{ icon('memory') }} Équipement</a></li>
        <li><a href="{{ path('room') }}" {{ menu_active('room') }}>{{ icon('view_in_ar') }} Salle multimédia</a></li>
        <li><a href="{{ path('orders.user') }}" {{ menu_active('myOrder') }}>{{ icon('receipt_long') }} Mes
                commandes</a>
        </li>
        <li><a href="{{ path('app.support') }}" {{ menu_active('support') }}>{{ icon('help_outline') }} Informations</a></li>
        {% if app.user.id is defined %}
            {% if app.user.isAdmin %}
            <li><a href="{{ path('admin.index') }}">{{ icon('tune') }} Administration</a></li>
            {% endif %}
        {% endif %}
    </ul>
    {{ include('components/_header-nav_side.html.twig') }}
</nav>

templates/components/_header-nav_side.html.twig
<ul class="header_side">
    {% if app.user %}
        <li class="header__cart">
            {{ include('components/_cart.html.twig') }}
        </li>
        <li class="header__account">
            <a href="{{ path('user.profil') }}" {{ menu_active('profil') }}>{{ icon('person_outline') }}<span class="header__account-username">{{ app.user }}</span></a>
        </li>
        <li class="header__logout">
            <a href="{{ path('app.logout') }}">{{ icon('logout') }}</a>
        </li>
    {% else %}
        <li class="header-side__auth">
            <a href="{{ path('app.login') }}" {{ menu_active('login') }}>{{ icon('person_outline') }} Se connecter</a>
            <span class="text-muted">•</span>
            <a href="{{ path('app_register') }}" {{ menu_active('register') }}>S'inscrire</a>
        </li>
    {% endif %}
    <li>
        <a href="#" class="mobile-menu-toggle">{{ icon('menu') }}</a>
    </li>
</ul>

templates/components/_header.html.twig
<nav class="header" style="--color-light: #8491c7;">
    <ul class="header-nav">
        <li class="header__home">
            <a href="{{ path('app.home') }}" {{ menu_active('home') }} title="Accueil">
                {{ icon('home') }}
            </a>
        </li>
        <li><a href="{{ path('hardware') }}" {{ menu_active('hardware') }}>{{ icon('memory') }} Matériel</a></li>
        <li><a href="{{ path('room') }}" {{ menu_active('room') }}>{{ icon('view_in_ar') }} Salle multimédia</a></li>
        <li><a href="{{ path('orders.user') }}" {{ menu_active('myOrder') }}>{{ icon('receipt_long') }} Mes
                commandes</a>
        </li>
        <li><a href="{{ path('app.support') }}" {{ menu_active('support') }}>{{ icon('help_outline') }} Support</a></li>
    </ul>
    {{ include('components/_header_side.html.twig') }}
</nav>

templates/components/_header_side.html.twig
<ul class="header_side">
    {% if app.user %}
        <li class="header__account">
            <a href="{{ path('user.profil') }}" {{ menu_active('profil') }}>{{ icon('person_outline') }} {{ app.user }}</a>
        </li>
        <li class="header__logout">
            <a href="{{ path('app.logout') }}">{{ icon('logout') }}</a>
        </li>
    {% else %}
        <li class="header-side__auth">
            <a href="{{ path('app.login') }}" {{ menu_active('login') }}>{{ icon('person_outline') }} Se connecter</a>
            <span class="text-muted">•</span>
            <a href="{{ path('app_register') }}" {{ menu_active('register') }}>S'inscrire</a>
        </li>
    {% endif %}
</ul>

templates/components/_my-order_nav.html.twig
<nav class="order-card__nav">
    <a href="{{ path('orders.user.show', {id: order.id}) }}" class="order-card__nav-element" {{ tab_active('show.summary') }}>Résumé</a>
    {% if order.errorState is not same as(null) %}<a href="{{ path('orders.user.show.error', {id: order.id}) }}" class="order-card__nav-element nav-element-error" {{ tab_active('show.error') }}>{{ feather('alert-octagon') }} <span>Erreur</span></a>{% endif %}
    <a href="{{ path('orders.user.show.equipment', {id: order.id}) }}" class="order-card__nav-element" {{ tab_active('show.equipment') }}>Équipement</a>
    <a href="{{ path('orders.user.show.chronology', {id: order.id}) }}" class="order-card__nav-element" {{ tab_active('show.chronology') }}>Chronologie</a>
    {#<a href="{{ path('orders.user.show.actions', {id: order.id}) }}" class="order-card__nav-element" {{ tab_active('show.actions') }}>Actions</a>#}

    <a href="{{ path('pdf.order.client', {'id': order.id}) }}" class="order-dl-btn" style="transform: none; height: fit-content; margin-left: auto" target="_blank">{{ feather('arrow-down-circle') }} Bon de commande</a>
</nav>

templates/components/_order.html.twig
<article class="order">
    <div class="order-col">
        <div class="order-col__title">
            <span>ID</span>
        </div>
        <div class="order-col__value">
            <h5>000002</h5>
        </div>
    </div>
    <div class="order-col">
        <div class="order-col__title">
            <span>Nom du projet</span>
        </div>
        <div class="order-col__value">
            <h5>Portfolio</h5>
        </div>
    </div>

    <div class="order-col">
        <div class="order-col__title">
            <span>Date de création</span>
        </div>
        <div class="order-col__value">
            <h5>3 mars 2022</h5>
        </div>
    </div>

    <div class="order-col">
        <div class="order-col__title">
            <span>Bon de commande</span>
        </div>
        <div class="order-col__value">
            <a href="#" class="order-dl-btn">{{ feather('clipboard') }} Télécharger</a>
        </div>
    </div>

    <div class="order-col">
        <div class="order-col__title">
            <span>Statut</span>
        </div>
        <div class="order-col__value">
            <span class="pill small-round">Terminée</span>
        </div>
    </div>

    <div class="order-col">
        <a href="#" class="order-btn">{{ feather('chevron-right') }}</a>
    </div>
</article>